Hm3 brod9ga
Brod9ga/nodejs-homework-restAPI pull request #5
Opened 2023-09-15 20:49 UTC by Brod9ga

2023-09-16 07:09 UTC, ceREAL133 requested changes

2023-09-16 07:09 UTC, ceREAL133 commented on models/contacts.js
> +// const updateContacts = (contacts) =>
видалити коменти

2023-09-16 07:09 UTC, ceREAL133 commented on models/contacts.js
> +//   const contacts = await listContacts();
видалити коменти

2023-09-16 07:09 UTC, ceREAL133 commented on routes/api/contacts.js
>  router.get('/', async (req, res, next) => {
всі функції в роутері мають бути описані в окремому файлі- контролері. В роутері вони мають тільки викликатись

2023-09-16 07:09 UTC, ceREAL133 commented on server.js
> + const DB_HOST = 'mongodb+srv://Brod9ga:7P9ICK90aYeSY1yn@cluster0.pgs52lm.mongodb.net/MyContacts?retryWrites=true&w=majority'
конекшн строка має бути в .env

2023-09-17 11:39 UTC, Brod9ga reviewed
fix

2023-09-20 13:16 UTC, ceREAL133 approved these changes

2023-09-20 18:07 UTC, merged